name = "Dalt"
uuid = "36869731-bdee-424d-aa32-cab38c994e3b"
authors = ["Sergio Alejandro Vargas <savargasqu+git@unal.edu.co>"]
version = "0.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
